# Configuration for Equinix API specs
apis:
  # Metal API - uses different auth (X-Auth-Token) and base path
  metal:
    auth_type: "metal_token"
    service_name: "metal"
    include:
      - metal_findPlans
      - metal_findMetros
    specs:
      - url: "https://docs.equinix.com/api-catalog/metalv1/openapi.yaml"
        overlay: "overlays/metal.yaml"

  # Network Edge API
  network-edge:
    auth_type: "client_credentials"
    service_name: "network-edge"
    enabled: true
    specs:
      - url: "https://docs.equinix.com/api-catalog/network-edgev1/openapi.yaml"
        overlay: "overlays/network-edge.yaml"

  # Fabric API
  fabric:
    auth_type: "client_credentials"
    service_name: "fabric"
    include:
      - fabric_searchConnections
      - fabric_searchProviders
      - fabric_getMetros
    specs:
      - url: "https://docs.equinix.com/api-catalog/fabricv4/openapi.yaml"
        overlay: "overlays/fabric.yaml"

  # Billing API
  billing:
    auth_type: "client_credentials"
    service_name: "billing"
    specs:
      - url: "https://docs.equinix.com/api-catalog/billingv2/openapi.yaml"
        overlay: "overlays/billing.yaml"
  # SmartView APIs
  smartview:
    specs:
      - url: "https://docs.equinix.com/api-catalog/environmentalv1/openapi.yaml"
      - url: "https://docs.equinix.com/api-catalog/environmentalv2/openapi.yaml"
      - url: "https://docs.equinix.com/api-catalog/feed-subscriptionv2/openapi.yaml"
      - url: "https://docs.equinix.com/api-catalog/hierarchyv1/openapi.yaml"
      - url: "https://docs.equinix.com/api-catalog/ibx-assetsv1/openapi.yaml"
      - url: "https://docs.equinix.com/api-catalog/powerv1/openapi.yaml"
      - url: "https://docs.equinix.com/api-catalog/system-alertsv2/openapi.yaml"

# Authentication configuration
auth:
  # Client Credentials flow for most APIs
  client_credentials:
    token_url: "https://api.equinix.com/oauth2/v1/token"

  # Metal API uses different auth
  metal_token:
    header_name: "X-Auth-Token"

# Output configuration
output:
  merged_spec_path: "merged-openapi.yaml"

# Documentation configuration
docs:
  sitemap_url: "https://docs.equinix.com/sitemap.xml"
  cache_path: "docs/sitemap_cache.xml"
