name: Update API Specs

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      create_pr:
        description: 'Create a PR with updates'
        required: false
        default: 'true'
        type: boolean

jobs:
  update-specs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        
    - name: Update API specs
      run: |
        equinix-mcp-server --update-specs
        
    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit changes
      if: steps.changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "chore: update API specs $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        
    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true' && (github.event.inputs.create_pr == 'true' || github.event_name == 'schedule')
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update API specs $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        title: "Update API Specs"
        body: |
          This PR contains automated updates to the API specifications.
          
          ## Changes
          - Updated OpenAPI specs from Equinix API catalog
          - Regenerated merged specification
          - Updated overlay files if needed
          
          ## What to review
          - Check that the merged spec is valid
          - Verify that new endpoints are properly categorized
          - Review any changes to authentication schemes
          
          Auto-generated by GitHub Actions.
        branch: update-api-specs
        delete-branch: true
        
    - name: Summary
      run: |
        if [[ "${{ steps.changes.outputs.changes }}" == "true" ]]; then
          echo "✅ API specs were updated"
          if [[ "${{ github.event.inputs.create_pr }}" == "true" || "${{ github.event_name }}" == "schedule" ]]; then
            echo "📋 Pull request created"
          else
            echo "💾 Changes committed to current branch"
          fi
        else
          echo "ℹ️ No changes detected in API specs"
        fi